// This file will be generated by Supabase CLI
// For now, we'll define basic types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          github_username: string | null
          github_access_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      organizations: {
        Row: {
          id: string
          github_id: number
          login: string
          name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          github_id: number
          login: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          github_id?: number
          login?: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      repositories: {
        Row: {
          id: string
          github_id: number
          organization_id: string
          name: string
          full_name: string
          private: boolean
          description: string | null
          default_branch: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          github_id: number
          organization_id: string
          name: string
          full_name: string
          private?: boolean
          description?: string | null
          default_branch?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          github_id?: number
          organization_id?: string
          name?: string
          full_name?: string
          private?: boolean
          description?: string | null
          default_branch?: string
          created_at?: string
          updated_at?: string
        }
      }
      pull_requests: {
        Row: {
          id: string
          github_id: number
          repository_id: string
          number: number
          title: string
          state: 'open' | 'closed' | 'merged'
          author_username: string
          created_at: string
          updated_at: string
          closed_at: string | null
          merged_at: string | null
          review_comments_count: number
          commits_count: number
          additions: number
          deletions: number
        }
        Insert: {
          id?: string
          github_id: number
          repository_id: string
          number: number
          title: string
          state: 'open' | 'closed' | 'merged'
          author_username: string
          created_at: string
          updated_at: string
          closed_at?: string | null
          merged_at?: string | null
          review_comments_count?: number
          commits_count?: number
          additions?: number
          deletions?: number
        }
        Update: {
          id?: string
          github_id?: number
          repository_id?: string
          number?: number
          title?: string
          state?: 'open' | 'closed' | 'merged'
          author_username?: string
          created_at?: string
          updated_at?: string
          closed_at?: string | null
          merged_at?: string | null
          review_comments_count?: number
          commits_count?: number
          additions?: number
          deletions?: number
        }
      }
      issues: {
        Row: {
          id: string
          github_id: number
          repository_id: string
          number: number
          title: string
          state: 'open' | 'closed'
          author_username: string
          assignee_username: string | null
          labels: string[]
          created_at: string
          updated_at: string
          closed_at: string | null
        }
        Insert: {
          id?: string
          github_id: number
          repository_id: string
          number: number
          title: string
          state: 'open' | 'closed'
          author_username: string
          assignee_username?: string | null
          labels?: string[]
          created_at: string
          updated_at: string
          closed_at?: string | null
        }
        Update: {
          id?: string
          github_id?: number
          repository_id?: string
          number?: number
          title?: string
          state?: 'open' | 'closed'
          author_username?: string
          assignee_username?: string | null
          labels?: string[]
          created_at?: string
          updated_at?: string
          closed_at?: string | null
        }
      }
      commits: {
        Row: {
          id: string
          repository_id: string
          sha: string
          author_username: string
          author_email: string | null
          message: string
          additions: number
          deletions: number
          committed_at: string
          created_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          sha: string
          author_username: string
          author_email?: string | null
          message: string
          additions?: number
          deletions?: number
          committed_at: string
          created_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          sha?: string
          author_username?: string
          author_email?: string | null
          message?: string
          additions?: number
          deletions?: number
          committed_at?: string
          created_at?: string
        }
      }
      ai_suggestions: {
        Row: {
          id: string
          repository_id: string
          user_id: string
          suggestion_type: string
          title: string
          content: string
          metadata: Json
          is_applied: boolean
          created_at: string
          expires_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          user_id: string
          suggestion_type: string
          title: string
          content: string
          metadata?: Json
          is_applied?: boolean
          created_at?: string
          expires_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          user_id?: string
          suggestion_type?: string
          title?: string
          content?: string
          metadata?: Json
          is_applied?: boolean
          created_at?: string
          expires_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 