// This file will be generated by Supabase CLI
// For now, we'll define basic types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          github_username: string | null
          github_access_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      repositories: {
        Row: {
          id: string
          github_id: number
          user_id: string
          name: string
          full_name: string
          private: boolean
          description: string | null
          default_branch: string
          github_url: string | null
          clone_url: string | null
          last_analyzed_at: string | null
          analysis_status: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          github_id: number
          user_id: string
          name: string
          full_name: string
          private?: boolean
          description?: string | null
          default_branch?: string
          github_url?: string | null
          clone_url?: string | null
          last_analyzed_at?: string | null
          analysis_status?: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          github_id?: number
          user_id?: string
          name?: string
          full_name?: string
          private?: boolean
          description?: string | null
          default_branch?: string
          github_url?: string | null
          clone_url?: string | null
          last_analyzed_at?: string | null
          analysis_status?: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          repository_id: string
          document_path: string
          title: string
          content: string
          document_type: 'file' | 'class' | 'function' | 'module' | 'overview'
          file_path: string | null
          line_start: number | null
          line_end: number | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          document_path: string
          title: string
          content: string
          document_type: 'file' | 'class' | 'function' | 'module' | 'overview'
          file_path?: string | null
          line_start?: number | null
          line_end?: number | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          document_path?: string
          title?: string
          content?: string
          document_type?: 'file' | 'class' | 'function' | 'module' | 'overview'
          file_path?: string | null
          line_start?: number | null
          line_end?: number | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      document_links: {
        Row: {
          id: string
          source_document_id: string
          target_document_id: string
          link_type: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references'
          created_at: string
        }
        Insert: {
          id?: string
          source_document_id: string
          target_document_id: string
          link_type: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references'
          created_at?: string
        }
        Update: {
          id?: string
          source_document_id?: string
          target_document_id?: string
          link_type?: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references'
          created_at?: string
        }
      }
      analysis_logs: {
        Row: {
          id: string
          repository_id: string
          analysis_type: 'full' | 'incremental'
          status: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at: string
          completed_at: string | null
          error_message: string | null
          files_analyzed: number
          documents_generated: number
        }
        Insert: {
          id?: string
          repository_id: string
          analysis_type?: 'full' | 'incremental'
          status?: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          files_analyzed?: number
          documents_generated?: number
        }
        Update: {
          id?: string
          repository_id?: string
          analysis_type?: 'full' | 'incremental'
          status?: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          files_analyzed?: number
          documents_generated?: number
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 