// This file will be generated by Supabase CLI
// For now, we'll define basic types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          github_username: string | null
          github_access_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          github_username?: string | null
          github_access_token?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      repositories: {
        Row: {
          id: string
          github_id: number
          user_id: string
          name: string
          full_name: string
          private: boolean
          description: string | null
          default_branch: string
          github_url: string | null
          clone_url: string | null
          last_analyzed_at: string | null
          analysis_status: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          github_id: number
          user_id: string
          name: string
          full_name: string
          private?: boolean
          description?: string | null
          default_branch?: string
          github_url?: string | null
          clone_url?: string | null
          last_analyzed_at?: string | null
          analysis_status?: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          github_id?: number
          user_id?: string
          name?: string
          full_name?: string
          private?: boolean
          description?: string | null
          default_branch?: string
          github_url?: string | null
          clone_url?: string | null
          last_analyzed_at?: string | null
          analysis_status?: 'pending' | 'analyzing' | 'completed' | 'failed'
          created_at?: string
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          repository_id: string
          document_path: string
          title: string
          content: string
          document_type: 'file' | 'class' | 'function' | 'module' | 'overview' | 'system' | 'workflow' | 'component' | 'service'
          file_path: string | null
          line_start: number | null
          line_end: number | null
          summary: string | null
          component_ids: Json | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          document_path: string
          title: string
          content: string
          document_type: 'file' | 'class' | 'function' | 'module' | 'overview' | 'system' | 'workflow' | 'component' | 'service'
          file_path?: string | null
          line_start?: number | null
          line_end?: number | null
          summary?: string | null
          component_ids?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          document_path?: string
          title?: string
          content?: string
          document_type?: 'file' | 'class' | 'function' | 'module' | 'overview' | 'system' | 'workflow' | 'component' | 'service'
          file_path?: string | null
          line_start?: number | null
          line_end?: number | null
          summary?: string | null
          component_ids?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      document_links: {
        Row: {
          id: string
          source_document_id: string
          target_document_id: string
          link_type: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references' | 'depends_on' | 'composes' | 'exposes' | 'tests'
          created_at: string
        }
        Insert: {
          id?: string
          source_document_id: string
          target_document_id: string
          link_type: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references' | 'depends_on' | 'composes' | 'exposes' | 'tests'
          created_at?: string
        }
        Update: {
          id?: string
          source_document_id?: string
          target_document_id?: string
          link_type?: 'imports' | 'uses' | 'extends' | 'implements' | 'calls' | 'references' | 'depends_on' | 'composes' | 'exposes' | 'tests'
          created_at?: string
        }
      }
      artifacts: {
        Row: {
          id: string
          repository_id: string
          artifact_id: string
          path: string
          language: string | null
          size: number | null
          hash: string | null
          artifact_type: string
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          artifact_id: string
          path: string
          language?: string | null
          size?: number | null
          hash?: string | null
          artifact_type: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          artifact_id?: string
          path?: string
          language?: string | null
          size?: number | null
          hash?: string | null
          artifact_type?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      components: {
        Row: {
          id: string
          repository_id: string
          component_id: string
          name: string
          component_type: string
          parent_path: string | null
          start_line: number | null
          end_line: number | null
          relations: Json
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          component_id: string
          name: string
          component_type: string
          parent_path?: string | null
          start_line?: number | null
          end_line?: number | null
          relations?: Json
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          component_id?: string
          name?: string
          component_type?: string
          parent_path?: string | null
          start_line?: number | null
          end_line?: number | null
          relations?: Json
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      planning_sessions: {
        Row: {
          id: string
          repository_id: string
          session_type: 'full' | 'incremental'
          status: 'planning' | 'generating' | 'completed' | 'failed'
          work_plan: Json | null
          started_at: string
          completed_at: string | null
          error_message: string | null
          metadata: Json
        }
        Insert: {
          id?: string
          repository_id: string
          session_type?: 'full' | 'incremental'
          status?: 'planning' | 'generating' | 'completed' | 'failed'
          work_plan?: Json | null
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          metadata?: Json
        }
        Update: {
          id?: string
          repository_id?: string
          session_type?: 'full' | 'incremental'
          status?: 'planning' | 'generating' | 'completed' | 'failed'
          work_plan?: Json | null
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          metadata?: Json
        }
      }
      context_cache: {
        Row: {
          id: string
          repository_id: string
          cache_key: string
          context_data: Json
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          cache_key: string
          context_data: Json
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          cache_key?: string
          context_data?: Json
          expires_at?: string
          created_at?: string
        }
      }
      generation_metrics: {
        Row: {
          id: string
          repository_id: string
          document_id: string
          model_used: string
          tokens_input: number
          tokens_output: number
          cost_estimated: number | null
          generation_time_ms: number | null
          created_at: string
        }
        Insert: {
          id?: string
          repository_id: string
          document_id: string
          model_used: string
          tokens_input: number
          tokens_output: number
          cost_estimated?: number | null
          generation_time_ms?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          repository_id?: string
          document_id?: string
          model_used?: string
          tokens_input?: number
          tokens_output?: number
          cost_estimated?: number | null
          generation_time_ms?: number | null
          created_at?: string
        }
      }
      analysis_logs: {
        Row: {
          id: string
          repository_id: string
          analysis_type: 'full' | 'incremental'
          status: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at: string
          completed_at: string | null
          error_message: string | null
          files_analyzed: number
          documents_generated: number
        }
        Insert: {
          id?: string
          repository_id: string
          analysis_type?: 'full' | 'incremental'
          status?: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          files_analyzed?: number
          documents_generated?: number
        }
        Update: {
          id?: string
          repository_id?: string
          analysis_type?: 'full' | 'incremental'
          status?: 'pending' | 'in_progress' | 'completed' | 'failed'
          started_at?: string
          completed_at?: string | null
          error_message?: string | null
          files_analyzed?: number
          documents_generated?: number
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 